server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: myspringbootapp

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/myapp}
    username: ${SPRING_DATASOURCE_USERNAME:appuser}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.rcfsoft: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

---
# Local development profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
# Production profile
spring:
  config:
    activate:
      on-profile: production
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.rcfsoft: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
